### ISSUE TITLE
Document how to run the test locally in Windows

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wms13-dgiwg#2]
Please document how to run the test via command line and also in non-interactive mode. Provide examples and screenshots as needed. More information here:
http://opengeospatial.github.io/teamengine/users.html

Document in the wiki: https://github.com/opengeospatial/ets-dgiwg-wms13/wiki/Instructions-to-run-the-test-locally

**Comment by keshavnangare** [comment]
Whenever I am trying to execute the test through the command line it is failing with the error:


```

C:\>te-install\bin\windows\test.bat -source=C:\TE_BASE\scripts\dgiwg-wms13\2.1.0\ctl\wms-suite.ctl
Testing suite tns:ets-dgiwg-wms13-0.3-SNAPSHOT in Test Mode with defaultResult of Pass ...
******************************************************************************************************************************
   Testing tns:Main type Mandatory in Test Mode with defaultResult Pass (s0095)...
      Assertion: The test subject satisfies all applicable constraints.
Dec 09, 2016 6:42:09 PM com.occamlab.te.TECore setFormResults
INFO: Setting form results:
 <?xml version="1.0" encoding="UTF-8"?>
<values>
   <value key="wms-uri">http://elevation2.arcgis.com/arcgis/services/Polar/ArcticDEM_map/MapServer/WMSServer?request=GetCapabilities&amp;service=WMS</value>
   <value key="wms-vector">no</value>
</values>
Fatal Error: Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo)
 throws java.lang.Exception}: Exception in extension function java.lang.NullPointerException; SystemID: file:/C:/Users/keshav/teamengine/work/TE_BASE_scripts_dgiwg-wms13_2.1.0_ctl_wms-suite.ctl/tns$Main.test; Line#: 75; Column#: -1
Dec 09, 2016 6:42:09 PM com.occamlab.te.TECore executeTest
SEVERE: Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) thro
ws java.lang.Exception}: Exception in extension function java.lang.NullPointerException
   Test tns:Main Failed
                        See the detail test Report C:\Users\keshav\teamengine\users\keshav/s0095/log.xml
                        See the detail error Report C:\Users\keshav\teamengine\users\keshav/s0095/error_log/log.txt
Suite tns:ets-dgiwg-wms13-0.3-SNAPSHOT Failed
```

```

`2016/12/09-18:42:09 ERROR
Test Name : tns:Main type Mandatory
net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function java.lang.NullPointerException
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:192)
	at com.occamlab.te.TECore.executeTemplate(TECore.java:576)
	at com.occamlab.te.TECore.executeTest(TECore.java:787)
	at com.occamlab.te.TECore.execute_test(TECore.java:395)
	at com.occamlab.te.TECore.execute_suite(TECore.java:443)
	at com.occamlab.te.TECore.execute(TECore.java:300)
	at com.occamlab.te.Test.execute(Test.java:318)
	at com.occamlab.te.Test.main(Test.java:91)
Caused by: net.sf.saxon.trans.XPathException: Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function java.lang.NullPointerException
	at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:151)
	at net.sf.saxon.expr.Expression.evaluateItem(Expression.java:352)
	at net.sf.saxon.expr.Expression.process(Expression.java:461)
	at net.sf.saxon.instruct.DocumentInstr.evaluateItem(DocumentInstr.java:282)
	at net.sf.saxon.expr.ExpressionTool.evaluate(ExpressionTool.java:295)
	at net.sf.saxon.expr.LetExpression.eval(LetExpression.java:341)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:542)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Instruction.process(Instruction.java:94)
	at net.sf.saxon.expr.LetExpression.process(LetExpression.java:380)
	at net.sf.saxon.instruct.ForEach.processLeavingTail(ForEach.java:300)
	at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:175)
	at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:343)
	at net.sf.saxon.Controller.transformDocument(Controller.java:1736)
	at net.sf.saxon.Controller.transform(Controller.java:1560)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:190)
	... 7 more
Caused by: java.lang.NullPointerException
	at com.occamlab.te.TECore.callFunction(TECore.java:1133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sf.saxon.functions.ExtensionFunctionCall.invokeMethod(ExtensionFunctionCall.java:533)
	at net.sf.saxon.functions.ExtensionFunctionCall.call(ExtensionFunctionCall.java:256)
	at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:147)
	... 22 more

`
```

**Comment by rjmartell** [comment]
This is a TestNG suite; it should be run in a command terminal by calling the main class (de.latlon.ets.wms13.dgiwg.WmsDgiwgTestNGController) like any other Java-based suite. I will add the "aio" (all-in-one, executable uber JAR) assembly to make this more convenient.
